name: SCA with OWASP Dependency-Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Run OWASP Dependency-Check
        run: ./gradlew dependencyCheckAnalyze

      - name: Upload SCA report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: build/reports/dependency-check-report.html
